version: '3' 
services:
     nginx: 
        image: nginx:latest 
        ports: 
            - "80:80" 
        volumes:
             - .:/home/eritip
             - ./config/nginx:/etc/nginx.conf.d
        depends_on:
             - web
        #web 실행 후 nginx실행되게
     web: 
        build: 
            context: .
            dockerfile: Dockerfile
        command: gunicorn --bind 0:5000 "eri:create_app()"
        
        volumes:
             - .:/home/eritip
        expose:
             - "5000"
        #ports:
        #    - "5000:5000"
