"""empty message

Revision ID: 0219c7d6ad49
Revises: 8c350c5d1987
Create Date: 2021-05-20 23:40:35.853835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0219c7d6ad49'
down_revision = '8c350c5d1987'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('infoLink',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=20), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('infoLink')
    # ### end Alembic commands ###
