"""empty message

Revision ID: 58e55252d4af
Revises: d848cb16b7de
Create Date: 2021-05-04 18:13:08.338111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e55252d4af'
down_revision = 'd848cb16b7de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('haksikChangbo',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('whenEat', sa.String(length=10), nullable=False),
    sa.Column('menu', sa.String(length=100), nullable=False),
    sa.Column('price', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('haksikChangeui',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('whenEat', sa.String(length=10), nullable=False),
    sa.Column('menu', sa.String(length=100), nullable=False),
    sa.Column('price', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('haksikFoodcourt',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('whenEat', sa.String(length=10), nullable=False),
    sa.Column('menu', sa.String(length=100), nullable=False),
    sa.Column('price', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('haksikGyozik',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('whenEat', sa.String(length=10), nullable=False),
    sa.Column('menu', sa.String(length=100), nullable=False),
    sa.Column('price', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    op.create_table('haksikHaksaeng',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('whenEat', sa.String(length=10), nullable=False),
    sa.Column('menu', sa.String(length=100), nullable=False),
    sa.Column('price', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('haksikHaksaeng')
    op.drop_table('haksikGyozik')
    op.drop_table('haksikFoodcourt')
    op.drop_table('haksikChangeui')
    op.drop_table('haksikChangbo')
    # ### end Alembic commands ###
