"""empty message

Revision ID: 8c350c5d1987
Revises: ddf5b3c26e8a
Create Date: 2021-05-20 03:18:59.526895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c350c5d1987'
down_revision = 'ddf5b3c26e8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatLog',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('client', sa.String(length=100), nullable=True),
    sa.Column('bot', sa.String(length=100), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatLog')
    # ### end Alembic commands ###
