"""empty message

Revision ID: bf9065e7a9bc
Revises: 58e55252d4af
Create Date: 2021-05-04 18:45:12.460662

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bf9065e7a9bc'
down_revision = '58e55252d4af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('haksikTable',
    sa.Column('idx', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('whenEat', sa.String(length=10), nullable=False),
    sa.Column('menu', sa.String(length=100), nullable=False),
    sa.Column('price', sa.String(length=10), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('idx')
    )
    op.drop_table('haksikGyozik')
    op.drop_table('haksikChangbo')
    op.drop_table('haksikChangeui')
    op.drop_table('haksikFoodcourt')
    op.drop_table('haksikHaksaeng')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('haksikHaksaeng',
    sa.Column('idx', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('whenEat', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('menu', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('price', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('idx'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('haksikFoodcourt',
    sa.Column('idx', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('whenEat', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('menu', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('price', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('idx'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('haksikChangeui',
    sa.Column('idx', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('whenEat', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('menu', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('price', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('idx'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('haksikChangbo',
    sa.Column('idx', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('whenEat', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('menu', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('price', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('idx'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('haksikGyozik',
    sa.Column('idx', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('whenEat', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('menu', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('price', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.PrimaryKeyConstraint('idx'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('haksikTable')
    # ### end Alembic commands ###
